name: cropmask
dependencies:
 - numpy
 - scipy
 - Pillow
 - cython
 - matplotlib
 - scikit-image
 - tensorflow>=1.3.0
 - keras>=2.0.8
 - h5py
 - IPython[all]
 - rasterio
 - shapely
 - fiona
 - geopandas
 - descartes

